### ISSUE TITLE
Menu!

### ISSUE THREAD

**Issue by idylicaro** [kevenny03/Projeto-P2#2]
tem q fazer um menu antes do login.
então podemos colocar ,
1.login
2.Cadastro
3. Sair

você que criou o login @ @kevenny03 tem como vc fazer essa alteração?

**Comment by KevennyJS** [comment]
Tem sim, farei ela hoje!

Em ter, 23 de jul de 2019 14:34, Idyl Icaro dos Santos <
notifications@github.com> escreveu:
